---
# yaml-language-server: $schema=https://raw.githubusercontent.com/zarf-dev/zarf/main/zarf.schema.json
kind: ZarfPackageConfig
metadata:
  name: grafana
  version: 9.2.7-bb.0
  source: https://github.com/colonel-byte/zarf-pkg-big-bang
  annotations:
    org.opencontainers.image.source: "https://github.com/colonel-byte/zarf-pkg-big-bang"
components:
  - name: grafana
    required: true
    images:
      - registry1.dso.mil/bigbang/grafana:9.2.7-bb.0
      - registry1.dso.mil/ironbank/big-bang/base:2.1.0
      - registry1.dso.mil/ironbank/big-bang/grafana/grafana-plugins:12.0.2
      - registry1.dso.mil/ironbank/kiwigrid/k8s-sidecar:1.30.3
      - registry1.dso.mil/ironbank/opensource/bats/bats:1.12.0
      - registry1.dso.mil/ironbank/opensource/grafana/grafana-image-renderer:3.12.7
      - registry1.dso.mil/ironbank/redhat/ubi/ubi9-minimal:9.6
